### ISSUE TITLE
Code block not displayed correctly 

### ISSUE THREAD

**Issue by ahdbk** [79E/hexo-theme-quiet#21]
Hey all, Love the work you are doing with your theme.
I've installed the theme on my blog and I have this problem.
The code bloc is not displayed correctly 

Any hint or idea how to fix it ? 

Thanks
![image](https://user-images.githubusercontent.com/2827484/194764602-e6cd278b-ff4f-4236-8fd4-2a4a357240f2.png)

**Comment by 79W** [comment]
Check whether your configuration file is configured according to the
-------
```
# 我的配置
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```
